spring.application.name=posApps

spring.datasource.url=jdbc:postgresql://localhost:5432/pos_anugrah
spring.datasource.username=postgres
spring.datasource.password=1234

spring.thymeleaf.cache=false
server.servlet.session.timeout=12h
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB



